name: CI

on: [push]

jobs:
  test:
    name: Test on Node.js 12 running on macOS-latest
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Run hydrate tests
        run: cd hydrate/tests && npm install && npm test
